### ISSUE TITLE
Tests for a custom encoding of cookies

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [abarth/http-state#16]
Hi, I have built a lot of tests covering all the allowed and not allowed cookie values according to RFC 6265, which represents all characters allowed in all major browsers when the spec was created (and which seems to stand until today).

I am not sure what is the goal of this repo, but it might be useful somehow: https://github.com/js-cookie/js-cookie/blob/72d05c27ebfb99aa8b6ae8f1b46210e223e815b9/test/encoding.js

It runs in all relevant browsers including IE6: https://saucelabs.com/u/js-cookie

X-Ref: https://github.com/inikulin/cookie-compat/issues/4.

**Comment by abarth** [comment]
Neat.

If you like, you can send a pull request that adds a "Related Test Suites" second to the README that links to your project.  It think it's valuable for people to be able to find high quality test suites for cookies.

**Comment by FagnerMartinsBrack** [comment]
Closed from https://github.com/abarth/http-state/pull/17#issuecomment-242926081.
